### ISSUE TITLE
Add possibility to filter operation or parameters

### ISSUE THREAD

**Issue by aromanet42** [jrcodeza/spring-openapi#41]
Hello !

I just discovered your Generator, it seems to have a lot of possibilities!

I am documenting some legacy APIs. I have some constraints.

Could you add the possibilities to filter Operations or Parameters?

For Parameters, we could add a `shouldBeIncludedInDocumentation` in `OperationParameterInterceptor`, and it would be called in `com.github.jrcodeza.schema.generator.OperationsTransformer#transformParameters`.

For Operations, it would be called in `com.github.jrcodeza.schema.generator.OperationsTransformer#createOperation` or `com.github.jrcodeza.schema.generator.OperationsTransformer#updateOperationsMap` maybe?

What do you think?

**Comment by jrcodeza** [comment]
Hi @aromanet42 ,

thanks for input. we can consider adding methods as you suggest to interceptors, but first I would like to check other options. There is @OpenApiIgnore annotation using which you can ignore operations (methods) and also operation parameters. Is it possible for you to use this annotation or you cannot change the controller in any way? 

Thanks.

**Comment by aromanet42** [comment]
Hi @jrcodeza !

Thanks for the quick response!

I have a lot of Controllers. I want to document multiple set of APIs, depending on multiple criterias. For example, my APIs are `@Secured` with multiple ROLEs, and I want to generate one swagger file per role so I can have one API Documentation per use-case. 

I cannot use the `@OpenApiIgnore` annotation in this case, I need to filter the APIs with a custom logic: I need to check how my Java Method is annotated and decide to keep the API or not depending of those annotations.

By the way, I also need to filter Schema Fields.

Thanks!

**Comment by jrcodeza** [comment]
Hi @aromanet42 ,

thanks for insight in your use case :) for this kind of solution I agree that it's best to support it also in a custom way as you describe. Perhaps, I would rather create new structure for this called CustomFilter (similar as interceptors). You could set them as interceptors and implement e.g. shouldIgnore method. Because interceptor is more oriented to actually intercept generated outcome.

Do you agreee? Would you like to do the implementation yourself in this repo or should I have look? If I check it it would be available next week I think.

Thanks.

**Comment by aromanet42** [comment]
This solution looks good to me :+1: 

I will try to come out with a PR today or tomorrow

Thanks!

**Comment by aromanet42** [comment]
@jrcodeza 

Here is my PR: https://github.com/jrcodeza/spring-openapi/pull/43

WDYT?

**Comment by jrcodeza** [comment]
@aromanet42  I will check tomorrow morning and let you know, so far only scrolled quickly and looks fine :)

**Comment by jrcodeza** [comment]
Thanks for change. You changes are merged in master. I think I might do the release during weekend.

**Comment by aromanet42** [comment]
Thank you for your reactivity and advices
