### ISSUE TITLE
Externalise "MediaType" build in dedicated class

### ISSUE THREAD

**Issue by aromanet42** [jrcodeza/spring-openapi#44]
Hello!

I want to document some weird APIs.

Some are legacy and I cannot change the Java signature, but still want to document them. For example, they return some Foo object, but I want to document them as returning "Bar" object.
Some can for example return differents Schema depending on content-type. I don't think that your `com.github.jrcodeza.Response` can handle that, but OpenApi3 authorise that: https://swagger.io/docs/specification/describing-responses/

To allow users to handle all weird cases they might encounter, I propose to externalise all methods that can build `MediaType` in a public class that could be used by custom Interceptors.
For now, the `com.github.jrcodeza.schema.generator.OperationsTransformer#createMediaType` is private in OperationsTransformer and cannot be used outside this class.

WDYT?

**Comment by jrcodeza** [comment]
Hi,

yes you're right there are section which could be extracted and reused this way in interceptors for example. I think we can do this, the only implementation problem I see is that createMediaType uses generationContext but that can be refactored, because generationContext is used here only to retrieve if class is in allowed package. 

Do you also want to perform this change?

**Comment by aromanet42** [comment]
Hi,

Yes I can propose a PR for that! I think I can have something to show you today or monday.

Regards.

**Comment by aromanet42** [comment]
Hello @jrcodeza 

I think I'm lost with the GenerationContext refactoring...

Do you have an idea how to do that? 
I don't know how to do that properly :/

Thanks

**Comment by jrcodeza** [comment]
Hi @aromanet42 ,

this is sketch of my idea :) https://github.com/jrcodeza/spring-openapi/commit/74df63940fc9d9bcd5508d942f045ff0f5b60e28

**Comment by aromanet42** [comment]
Hi @jrcodeza 

I finally came up with https://github.com/jrcodeza/spring-openapi/pull/46

WDYT?

**Comment by jrcodeza** [comment]
Hi @aromanet42 ,

looks good. Only I would rename MediaTypeBuilder to something else, but looks better now when the complex methods are extracted to a dedicated class.

thanks

**Comment by jrcodeza** [comment]
PR merged

**Comment by jrcodeza** [comment]
@aromanet42  both issues you've worked on are released in 1.4.6 ;)

**Comment by aromanet42** [comment]
@jrcodeza so nice! thanks a lot!
